### ISSUE TITLE
estoy usando este script que es muy bueno para dispositivos gamma baja para runas rapidas de league of legens pero me da este error

### ISSUE THREAD

**Issue by NEPOXD21** [imranmaj/puppy#1]
Traceback (most recent call last):
  File "puppy\__main__.py", line 31, in <module>
  File "puppy\__init__.py", line 135, in main
AssertionError

no soy programador no se como intentar solucionarlo aca tienen mi discord para que se comuniquen conmigo si hay alguna solucion
NEPITOO#9512

**Comment by NEPOXD21** [comment]
you coan use the translator sorry for the spanish in your page

**Comment by imranmaj** [comment]
Hola, cuál versión usa? Por favor haga clic [aquí](https://github.com/imranmaj/puppy/releases/latest) y descarga la versión más nueva, entonces trátalo otra vez.

Lo siento, mi español no es muy bueno.

**Comment by NEPOXD21** [comment]
> Hola, ¿cuál versión usa? Por favor, haga clic [aquí](https://github.com/imranmaj/puppy/releases/latest) y descargue la versión más nueva, luego trátalo otra vez.
> 
> Lo siento, mi español no es muy bueno.

hi im using this upd so i think that no is the real problem we can chat in discrod maybe ist more easy

**Comment by imranmaj** [comment]
I would prefer to continue our discussion on GitHub.

Does this error still happen? If you try running it again, do you get the same error?

Also could you please tell me, when you got this error:

- what mode you were playing
- which map you were playing (Summoner's Rift or Howling Abyss)
- what champion you were playing
- what OS you were using (macOS or Windows)
- what backend you were using (U.GG or Mobalytics)

**Comment by imranmaj** [comment]
Closing due to inactivity. If you're still experiencing this problem on the latest version feel free to reopen or open a new issue.
