### ISSUE TITLE
it doesnt change the runes, check this error

### ISSUE THREAD

**Issue by Juan4e** [imranmaj/puppy#2]
when i lock the champ says

Locked in Akshan
Fetching data...
No data on current patch, attempting to revert to previous patch
Traceback (most recent call last):
  File "requests\models.py", line 960, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "puppy\apis\data\ugg\fetcher.py", line 74, in __init__
  File "requests\models.py", line 968, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "puppy\__main__.py", line 31, in <module>
  File "puppy\__init__.py", line 81, in main
  File "puppy\apis\data\ugg\ugg.py", line 48, in __init__
  File "puppy\apis\data\ugg\fetcher.py", line 109, in __init__
puppy.apis.data.exceptions.NoDataError: No data, champion=Akshan, queue=Summoner's Rift, rank=platinum_plus, patch=12_21

Press enter to exit...

help

**Comment by imranmaj** [comment]
Thank you for reporting this issue. I just created an update which I believe fixes the error. Please try using the latest version by downloading it from [the releases page](https://github.com/imranmaj/puppy/releases/tag/v1.3.1) and let me know if you still experience any issues.

**Comment by Juan4e** [comment]
damm bro you are a hero
