### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Juan4e** [imranmaj/puppy#3]
Locked in Rengar
Fetching data...
Traceback (most recent call last):
  File "puppy\__main__.py", line 31, in <module>
  File "puppy\__init__.py", line 81, in main
  File "puppy\apis\data\ugg\ugg.py", line 72, in __init__
  File "puppy\apis\data\ugg\fetcher.py", line 219, in rankings_data
puppy.apis.data.exceptions.NoDataError: No rankings for champion=Rengar, region=world, queue=Summoner's Rift, rank=platinum_plus, role=Middle

Press enter to exit...

**Comment by imranmaj** [comment]
Hi, please try again with the latest version of puppy, which you can download from [the releases page](https://github.com/imranmaj/puppy/releases). Let me know if the issue continues to appear.

**Comment by imranmaj** [comment]
Closing due to inactivity. If you're still experiencing this problem on the latest version feel free to reopen or open a new issue.
